name: Pull Request Action
on:
  push:
    branches:
      - feature/*
      
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2 # Set up Go environment
        with:
            go-version: '1.24.0' # Specify the Go version you want to use

      - name: Install dependencies
        run: go mod download # Download dependencies

      - name: Run tests # Run tests
        run: go test -v ./... # Added verbose flag for detailed test output

      - name: Save branch name to environment
        run: |
          sanitized_branch_name=$(echo "${{ github.ref_name }}" | sed 's/[^a-zA-Z0-9._-]/_/g')
          echo "SANITIZED_BRANCH_NAME=$sanitized_branch_name" >> $GITHUB_ENV
  
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "develop"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "feature, automated pr"
          pr_title: "PR criada automaticamente ${{ github.ref_name }}"
          pr_body: "This is an automated PR to merge changes from ${{ github.ref_name }} into develop."
          pr_draft: false