name: Pull Request Action
on:
  push:
    branches:
      - feature/*

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2 # Set up Go environment
        with:
            go-version: '1.24.0' # Specify the Go version you want to use

      - name: Install dependencies
        run: go mod download # Download dependencies

      - name: Run tests # Run tests
        run: go test -v ./... # Added verbose flag for detailed test output

      - name: Get the latest tag
        id: get_latest_tag
        run: |
          # Verifica se existem tags no repositório
          if [ $(git tag | wc -l) -eq 0 ]; then
            echo "Nenhuma tag encontrada. Criando a primeira tag."
            new_tag="v1.0.0"
          else
                # Obtém a última tag e incrementa
                latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
                echo "Última tag encontrada: $latest_tag"

                # Remove o prefixo 'v' da tag para manipulação numérica
                version_number=$(echo $latest_tag | sed 's/^v//')

                # Incrementa a última parte da versão
                new_version=$(echo $version_number | awk -F. '{$NF+=1; OFS="."; print $0}')

                # Adiciona o prefixo 'v' novamente
                new_tag="v$new_version"
                echo "Else: $new_tag"
          fi
          echo "Nova tag gerada: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_ENV

      - name: Create a Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.new_tag }}
          release_name: "Release ${{ env.new_tag }}"
        env:
          GITHUB_TOKEN: ${{ github.token }}

      
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "develop"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "feature, automated pr"
          pr_title: "PR criada automaticamente ${{ github.ref }}"
          pr_body: "This is an automated PR to merge changes from feature/* into develop."
          pr_draft: false