name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop
jobs:
    check-application:
        runs-on: ubuntu-latest # Use the latest Ubuntu runner
        steps:
            - name: Checkout code
              uses: actions/checkout@v2 # Check out the repository code

            - name: Set up Go
              uses: actions/setup-go@v2 # Set up Go environment
              with:
                  go-version: '1.24.0' # Specify the Go version you want to use

            - name: Install dependencies
              run: go mod download # Download dependencies

            - name: Run tests # Run tests
              run: go test -v ./... # Added verbose flag for detailed test output